app: skeleton
service: skeleton-db-build
useDotenv: true

provider:
  name: aws
  stage: dev
  region: eu-west-2
  runtime: provided.al2

plugins:
  - ./vendor/bref/bref

# For a pgDB inside a VPC look e.g. here:
# http://www.stojanveselinovski.com/blog/2016/01/12/simple-postgresql-rds-cloudformation-template/
resources:
  Resources:
    pgSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Access to Postgres
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: '5432'
            ToPort: '5432'
            CidrIp: 0.0.0.0/0
    pgDB:
      Type: "AWS::RDS::DBInstance"
      Properties:
        DBName: "${env:DB_NAME}"
        AllocatedStorage: 5
        DBInstanceClass: "db.t3.micro"
        BackupRetentionPeriod: 0
        Engine: "postgres"
        MasterUsername: "example"
        MasterUserPassword: "serverless"
        VPCSecurityGroups:
          - Fn::GetAtt:
              - pgSecurityGroup
              - GroupId
        Tags:
          -
            Key: "Name"
            Value: "forum_example"
      DeletionPolicy: "Snapshot"
  Outputs:
    pgEndpoint:
      Description: "JDBC connection string for database"
      Value:
        Fn::GetAtt:
          - pgDB
          - Endpoint.Address
# Exclude files from deployment
package:
  patterns:
    - '!node_modules/**'
    - '!tests/**'
